# config.py

coinbase_secret = '-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIDOVctxJpAI/hHtbUN9VrHej4bWPRuT9um9FoBlTgiyaoAoGCCqGSM49\nAwEHoUQDQgAEJt8JWIh8CHm045POImBF0ZvVuX5FbQjIDhIT82hE5r1+vb8cSQ3M\nfEjriBy1/ZD3EywPNxyGe6nO/Wsq0M8hXQ==\n-----END EC PRIVATE KEY-----\n'
coinbase_api = 'organizations/b6a02fc1-cbb0-4658-8bb2-702437518d70/apiKeys/697a8516-f2e2-4ec9-a593-464338d96f21'
kucoin_api = "65d92cc0291aa2000118b67b"
kucoin_secret = "3d449464-ab5e-4415-9950-ae31648fe90c"
kucoin_pass = "sN038-(!UK}4"
elastic_password = "P0H3MsMaUKy7=6jOi-Jx"

# password: HNtNChGd-2Id-9O_XXg_
#           P0H3MsMaUKy7=6jOi-Jx
# certificate SHA-256 fingerprint: e13b8081995a509320d2882434ec223657befe375fb81f7753565e030afecf9b
# kibana enrolement token: eyJ2ZXIiOiI4LjE0LjAiLCJhZHIiOlsiMTkyLjE2OC4xLjI1Mjo5MjAwIl0sImZnciI6ImUxM2I4MDgxOTk1YTUwOTMyMGQyODgyNDM0ZWMyMjM2NTdiZWZlMzc1ZmI4MWY3NzUzNTY1ZTAzMGFmZWNmOWIiLCJrZXkiOiIzUnlKYVpBQjJaU1RKQktrM2FHZjp0NzdGQ1Fta1RpYU9zR3NqTVZlVi1nIn0=
# nodes_enrolement_token = eyJ2ZXIiOiI4LjE0LjAiLCJhZHIiOlsiMTkyLjE2OC4xLjI1Mjo5MjAwIl0sImZnciI6ImUxM2I4MDgxOTk1YTUwOTMyMGQyODgyNDM0ZWMyMjM2NTdiZWZlMzc1ZmI4MWY3NzUzNTY1ZTAzMGFmZWNmOWIiLCJrZXkiOiIzaHlQYVpBQjJaU1RKQktra0tHajozUXJodkRQZ1Q3LVpSSVZUd05uM2ZnIn0=


kafka_configs = {
    "message.max.bytes": 0,  # Description: Maximum size of a message that the broker will accept.
                             # Typical Setting: Larger than your largest expected message size (e.g., 1MB if expecting large messages).

    "replica.fetch.max.bytes": 0,  # Description: Maximum number of bytes fetch requests are allowed to fetch from a single partition.
                                   # Typical Setting: Same or slightly larger than message.max.bytes.
    
    "fetch.message.max.bytes": 0,  # Description: Maximum number of bytes fetch requests are allowed to fetch from a single partition.
                                   # This must be at least as large as the largest message you want to fetch.
                                   # Typical Setting: Match with message.max.bytes.
    
    "num.network.threads": 0,  # Description: The number of threads that the server uses for processing requests, which are received over the network.
                               # Typical Setting: Depends on your server's hardware, but starting with a value equal to the number of cores is a good approach.
    
    "num.io.threads": 0,  # Description: The number of threads that perform disk I/O operations in the broker.
                          # Typical Setting: Equal to or greater than the number of storage devices.
    
    "socket.receive.buffer.bytes": 0,  # Description: The receive buffer (SO_RCVBUF) used by the network sockets.
                                       # Typical Setting: Increase if noticing network issues, typical values are 102400 (100KB) to 204800 (200KB).
    
    "socket.send.buffer.bytes": 0,  # Description: The send buffer (SO_SNDBUF) used by the network sockets.
                                    # Typical Setting: Same as socket.receive.buffer.bytes.
    
    "queued.max.request.bytes": 0,  # Description: The maximum number of bytes in the request queue.
                                    # A large request queue can handle a high volume of requests but may use more memory.
                                    # Typical Setting: Adjust based on memory availability and load.
    
    # Kafka Producer Configuration Parameters
    "max.request.size": 0,  # Description: Maximum size of a request that the producer can send.
                            # Typical Setting: Match or exceed message.max.bytes.
    
    "buffer.memory": 0,  # Description: Total bytes of memory the producer can use to buffer records waiting to be sent to the server.
                         # Typical Setting: Higher values can handle more records held during high traffic bursts.
    
    "compression.type": "none",  # Description: Specify the compression type for all data generated by the producer.
                                 # Options include none, gzip, snappy, lz4, or zstd.
                                 # Typical Setting: gzip or snappy for a balance between compression rate and CPU usage.
    
    "linger.ms": 0,  # Description: The producer will wait this long before sending records if the batch isn't filled.
                     # Typical Setting: Increases batch size and throughput at the cost of latency.
    
    "batch.size": 0,  # Description: Maximum number of bytes that will be included in a batch of messages.
                      # Typical Setting: Increase to maximize throughput, especially if you are sending large messages.
    
    "acks": "all",  # Description: The number of acknowledgments the producer requires from brokers.
                    # Typical Setting: all for ensuring full durability of records.
    
    "retry.backoff.ms": 0,  # Description: The amount of time to wait before attempting to retry a failed produce request.
                            # Typical Setting: Adjust based on your application's tolerance for retries.
}

default_price_value = 70000

# okx are SWAP for pepretual, FUTURE for futures and OPTION for options
okx_liquidations_inst_types = ["perpetual", "future"] #Okx only provides a unique stream for all liquidations. Those symbol found here will be processed others omited

#
okx_liquidations_symbols = {
        "process_type" : "basecoin", # basecoin, symbols
        "basecoin" : "BTC",  # Processes data of symbols with this basecoin
        "symbols" : []       # Processes only this symbols, if not empty. If empty then all
    } 


backup_symbols = { # you may cross symbols from different exchanges
    "binance" : "BTCUSDT@perpetual@binance",
    "bybit" : "BTCUSDT@perpetual@bybit",
    "okx" : "BTC-USDT-SWAP@perpetual@okx",
    "deribit" : "BTC-PERPETUAL@perpetual@deribit",
    "bitget" : "BTCUSDT@perpetual@bitget",
    "bingx" : "BTC-USDT@perpetual@bingx",
    "htx" : "BTCUSDT@perpetual@binance",
    "kucoin" : "XBTUSDTM@perpetual@kucoin",
    "mexc" : "BTC_USDT@perpetual@mexc",
    "gateio" : "BTC_USDT@perpetual@gateio",
}

merge_types = [
    "depth_spot", 
    "depth_future", 
    "trades_spot", 
    "trades_future", 
    "trades_option", 
    "oi_delta_future", 
    "liquidations_future",
    "oi_options", 
    "cdepth_spot", 
    "cdepth_future", 
    "rdepth_spot", 
    "rdepth_future"
    ]


message_processor_fail_threshold = 0.1


# MULTIPLIER CONFIGURATION

## BINANCE ###

# Contract values for Binance linear contracts (stablecoin/fiat-margined contracts) are standardized to 1 BTC,
# so no multiplication is needed.

# However, for coin-margined contracts, the contract values vary:
# - BTC contracts are worth 100 USD
# - Altcoin (other) contracts are worth 10 USD
# - If binance changes the contract values, this config file will need to be updated. simply add the basecoin and the following multiplier (ex : {"RBNB : 12"})

# This same principle applies to options contracts. But, options are worth in native coin.
binance_inverse_multipliers = {
            "BTC" : 100,
            "other" : 10
        }
binance_option_multipliers = {
            "BTC" : 1,
            "ETH" : 1,
            "BNB" : 1,
            "XRP" : 100,
            "DOGE" : 1000,
        }


### BYBIT ###

# Bybit USDT and USDC contracts worth 1 BTC, no need to multiply. 
# But, coin-marginated (inverse) contracts worth 1 usd. No need to config
# Options also worth 1 btc

### OKX ###
# okx is simmilar to binance though a bit different.
# if there is a lambda function instead of multiplier, its because the multiplier is worth in native coin rather than the stablecoin
okx_future_multipliers = {
    "USDT" : {
        "BTC" : lambda amount : amount * 0.01, 
        "ETH" : lambda amount : amount * 0.1, 
        "XLM" : 100,
        "TRX" : 1000,
        "other" : 10,
    },
    "USDC" : {
        "BTC" : lambda amount : amount * 0.0001,
        "ETH" : lambda amount : amount * 0.001,
        "XLM" : 100,
        "TRX" : 1000,
        "other" : 10, 
    },
    "USD" : {
        "XLM" : 100,
        "BTC" : 100,
        "TRX" : 1000,
        "other" : 10
    }
}
# options are worth in native coin 
okx_option_multipliers = {
            "BTC" : 0.01,
            "ETH " : 0.1,
            "LTC" : 1,
            "LINK" : 10,
            "DOT" : 10,
            "SOL" : 10,
            "ADA" : 100,
        }


### DERIBIT ###

deribit_future_multipliers = {
    "perpetual" : {
        "BTC-PERPETUAL" : lambda amount, price : amount  / price / 10,
        "ETH-PERPETUAL" : lambda amount, price : amount  / price,
        "ADA_USDC-PERPETUAL" : lambda amount, *args, **kwargs: amount * 10,
        "ALGO_USDC-PERPETUAL" : lambda amount, *args, **kwargs: amount * 10,
        "AVAX_USDC-PERPETUAL" : lambda amount, *args, **kwargs: amount * 0.1,
        "BCH_USDC-PERPETUAL" : lambda amount, *args, **kwargs: amount * 0.02,
        "BTC_USDC-PERPETUAL" : lambda amount, *args, **kwargs: amount * 0.001,
        "ETH_USDC-PERPETUAL" : lambda amount, *args, **kwargs: amount * 0.01,
        "LINK_USDC-PERPETUAL" : lambda amount, *args, **kwargs: amount,
        "LTC_USDC-PERPETUAL" : lambda amount, *args, **kwargs: amount * 0.1,
        "MATIC_USDC-PERPETUAL" : lambda amount, *args, **kwargs: amount * 10,
        "LINK_USDT-PERPETUAL" : lambda amount, *args, **kwargs: amount,
        "LTC_USDT-PERPETUAL" : lambda amount, *args, **kwargs: amount * 0.1,
        "NEAR_USDC-PERPETUAL" : lambda amount, *args, **kwargs: amount,
        "SOL_USDC-PERPETUAL" : lambda amount, *args, **kwargs: amount * 0.1,
        "TRX_USDC-PERPETUAL" : lambda amount, *args, **kwargs: amount * 100,
        "UNI_USDC-PERPETUAL" : lambda amount, *args, **kwargs: amount ,
        "XRP_USDC-PERPETUAL" : lambda amount, *args, **kwargs: amount * 10
    },
    "future" : {
    "BTC" : lambda amount, price : amount  / price / 10,
    "ETH" : lambda amount, price : amount  / price  
 }
}


deribit_option_multipliers = {
            "BTC" : 1,
            "ETH" : 1,
            "MATIC" : 1000,
            "SOL" : 10,
            "XRP" : 1000,
        }


### KUCOIN ###

# https://www.kucoin.com/pt/futures/contract/detail/ACEUSDTM
# Find you coin here and then add
kucoin_future_multipliers = {
    "XBTUSDTM" : 0.001,
    "XBTUSDTP" : 0.001,
    "XBTUSDM" : lambda amount, price: amount / price,
}


### MEXC ###
# https://www.mexc.com/support/articles/17827791509072
mexc_future_multipliers = {
    "BTC_USDT" : 0.0001,
    "BTC_USD" : lambda amount, price : amount * 100  / price
}

### GATEIO ###
# https://www.gate.io/futures_info_new/futures/usdt/BTC_USDT#baseinfo
gateio_future_multipliers = {
    "BTC_USDT" : 0.0001,
    "BTC_USD" : lambda amount, price : amount / price
}

gateio_option_multipliers = {
    "BTC_USDT" : 0.01,
    "ETH_USDT" : 0.01,
    "DOGE_USDT" : 1000,
}


fiats = [
    "usd", 
    "eur", 
    "rub", 
    "try", 
    "uah", 
    "kzt", 
    "inr", 
    "gbp", 
    "krw", 
    "aud", 
    "chf", 
    "czk", 
    "dkk", 
    "nok", 
    "nzd", 
    "pln", 
    "sek", 
    "zar", 
    "huf", 
    "ils"
]
stablecoins = [
    "usdt", 
    "usdc", 
    "busd", 
    "dai", 
    "tusd",
    "fdusd"
    ]