message.max.bytes: 1048576  # Maximum size of a message that the broker will accept.
replica.fetch.max.bytes: 1048576  # Maximum number of bytes fetch requests are allowed to fetch from a single partition.
fetch.message.max.bytes: 1048576  # Maximum number of bytes fetch requests are allowed to fetch from a single partition.
num.network.threads: 3  # Number of threads that the server uses for processing requests received over the network.
num.io.threads: 8  # Number of threads that perform disk I/O operations in the broker.
socket.receive.buffer.bytes: 102400  # The receive buffer (SO_RCVBUF) used by the network sockets.
socket.send.buffer.bytes: 102400  # The send buffer (SO_SNDBUF) used by the network sockets.
queued.max.request.bytes: 10485760  # Maximum number of bytes in the request queue.
max.request.size: 1048576  # Maximum size of a request that the producer can send.
buffer.memory: 33554432  # Total bytes of memory the producer can use to buffer records waiting to be sent to the server.
compression.type: gzip  # Specify the compression type for all data generated by the producer.
linger.ms: 1  # The producer will wait this long before sending records if the batch isn't filled.
batch.size: 16384  # Maximum number of bytes that will be included in a batch of messages.
acks: all  # The number of acknowledgments the producer requires from brokers.
retry.backoff.ms: 100  # The amount of time to wait before attempting to retry a failed produce request.